### ISSUE TITLE
Battery driven setup

### ISSUE THREAD

**Issue by larsbrinkhoff** [platisd/vasttraPi#1]
Hello,

I'd like to make something similar to this, except it supposed to be a wall-mounted clock.  I would like it to be powered off batteries instead.

Do you think there are low-power parts that can replace those you used?  I do need a 32-bit CPU running Linux in there, but it doesn't have to be quite as fast as an rPi.  I suppose the display draws most of the power anyway.  Monochrome without backlight is fine.

Thanks!

**Comment by larsbrinkhoff** [comment]
E ink?  OLED?

**Comment by platisd** [comment]
Hello Lars! Interesting inquiry!

So I assume you need something that is not expected to be updating or interacted with constantly and **should last about a month** (otherwise it is not fun, or is it?) on batteries. If you get a 10,000mAh powerbank you'd need your system's average consumption to be around... 15mA!

The single board Linux with the lowest consumption that I have used are the Raspberry Pi Zero and the Onion Omega. However they consume around one order of magnitude more, i.e. ~150mA. The worst part is that they lack a PMIC so there is little one can do to decrease that, by suspending to RAM.

My first suggestion would be to go for something that suspends to RAM in a really low power mode, but I could not find conclusive evidence of a specific board capable of this. The Beaglebone boards seem to support suspension to RAM but I could not find anything about the consumption during that state.

Therefore, due to the lack of a better and concrete solution, I would suggest a microcontroller periodically turning on the Linux machine.

Finally, I think an e-ink display is a must in any case, so to get the screen's consumption out of the equation.

**Comment by larsbrinkhoff** [comment]
Thanks!

Looks like I have to forego the battery.  In my intended application, there should be a PDP-10 emulator running continuously.  And I don't want to change/charge batteries every week.

Though, I hear Tesla makes large batteries...

**Comment by platisd** [comment]
I just saw what's this about. Cool! Unfortunately I do not think turning the computer on and off makes sense if you need to update the display every minute. :sweat: I had in mind a way slower refresh rate.

**Comment by larsbrinkhoff** [comment]
Every second, probably.

I think the processor could run somewhere around 100 MHz.  That might help.

**Comment by platisd** [comment]
I believe the operating frequency is not the most important factor, but rather the ability of the processor to pull the system into a really low power mode when not updating the screen. This is very easy to do with microcontrollers, but unfortunately I do not think it is possible/easy with what you are trying.

OK, while writing I got an idea! What about this setup: An inexpensive and low consumption movement sensor, that triggers a microcontroller to power on the Linux system when someone is actually around? For movement sensing I have the following options in mind:
* [PIR sensor](https://www.aliexpress.com/item/Free-Shipping-5PCS-HC-SR501-Adjust-IR-Pyroelectric-Infrared-PIR-module-Motion-Sensor-Detector-Module/32667738141.html): Detects whatever is moving within the line-of-sight towards all directions.

Or if you are feeling adventurous...
* [Microwave radar](https://www.aliexpress.com/item/5-8GHZ-Microwave-Radar-Sensor-Module-Smart-Sensoring-Switch-6-9M-Home-Control/32602485648.html?spm=a2g0s.9042311.0.0.DtO1Pj): Should be able to detect movement through walls, so you can turn on the system even before someone walks in the room!
I have tried one of these radars out, was not super satisfied with their performance but admittedly did not spend enough time to figure things out. I think they have a lot of potential.

From the user's perspective, the system is continuously on!

**Comment by larsbrinkhoff** [comment]
Good thinking outside the box, I like it!  Also bonus points for involving a microcontroller. :-)

**Comment by larsbrinkhoff** [comment]
I see now there are lamp sockets on the walls, so I probably won't need a battery.
